### ISSUE TITLE
F3-WG-Issue-6: Benefits of Route Targets [Swadesh Agrawal]

### ISSUE THREAD

**Issue by sa1231-coder** [ietf-wg-idr/draft-ietf-idr-bgp-car#11]
•	Chair + Keyur Patel + Swadesh Agrawal – Review F3-WG-issues-6 to generalize example. 
•	CT: Provide normative text and examples for non-agreeing color domains with examples on how transport class is used.  This example should include the example in F3-WG-issue-6 – which includes attaching multiple RTs to be used in different color domains is not practical
•	CAR: Provide normative text and examples for non-agreeing color domains.  Normative may require the authors to add additional text.  The examples should include the topology (similar or exactly like the topology above) with three color domains.

**Comment by sa1231-coder** [comment]
Section 2.8, 2.9.3 and Appendix B.3 describe the behavior, procedures and considerations for multiple color domains. This includes the rewrite of LCM at a color domain boundary peering.

**Comment by suehares** [comment]
Swadesh and DJ: 

Thank you for the rewrite in sections 2.8, 2.9.3, and B.3.  

Will you work with Keyur Patel to create a generalized example?   

After we get the generalized example, we'll start  WG List call on this topic with your text from -01.txt. 

Cheers, Sue

**Comment by suehares** [comment]
Sue will review 2.8, 2.9.3, and B.3 on Thursday (6/1/23)

Review as of 6/4/2023 on car-01. 
 
Section 2.8 - I do not have any issues. 
Section 2.9.3 - 

There are four places you indicate color exists:
1) CAR NLRI
2) Extended Community color 
3) LCM Extended Community, 
4) Tunnel Attribute - Color 

You clear indicated that #4) Tunnel attribute is ignored for color.  How does it impact filtering mentioned in section 2.9.3?  Can it be used.  Section 2.10 gives the ordering of these three color issues. 

Since we did not get a generalized example, we will ask early reviewers to examine this in their review.

**Comment by suehares** [comment]
Waiting for the final upload prior to external review. 
Think about error handling and filtering.

**Comment by sa1231-coder** [comment]
Agreed changes pushed in 02 version. WG queried as part of WGLC. No further comments received.

**Comment by sa1231-coder** [comment]
Agreed changes pushed in 02 version. WG queried as part of WGLC. No further comments received.
